/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Projects
         * @description Return all projects, optionally filtered by region, sector, or status.
         */
        get: operations["listProjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Project
         * @description Return a single project with computed headline KPIs.
         */
        get: operations["getProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/cost-trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Cost Trend
         * @description Return monthly cost time-series for a project, optionally scoped to a work package.
         */
        get: operations["getCostTrend"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/milestones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Milestones
         * @description Return schedule milestones for a project, ordered by planned date.
         */
        get: operations["listMilestones"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/change-orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Change Orders
         * @description Return change orders for a project, optionally filtered by status.
         */
        get: operations["listChangeOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/benchmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Project Benchmarks
         * @description Return benchmark comparisons for a project.
         */
        get: operations["getProjectBenchmarks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BenchmarkComparison
         * @description A project's unit-cost metric compared against sector/region peer distribution.
         */
        BenchmarkComparison: {
            /** Metrickey */
            metricKey: string;
            /** Unit */
            unit: string;
            /** Projectvalue */
            projectValue: number;
            /** Peermedian */
            peerMedian: number;
            /** Peerp25 */
            peerP25: number;
            /** Peerp75 */
            peerP75: number;
            position: components["schemas"]["BenchmarkPosition"];
        };
        /**
         * BenchmarkPosition
         * @enum {string}
         */
        BenchmarkPosition: "below_p25" | "p25_to_median" | "median_to_p75" | "above_p75";
        /**
         * ChangeOrder
         * @description A change order with cost and schedule impact.
         */
        ChangeOrder: {
            /** Id */
            id: string;
            /** Workpackageid */
            workPackageId?: string | null;
            /** Workpackagecode */
            workPackageCode?: string | null;
            /** Reference */
            reference: string;
            /** Title */
            title: string;
            status: components["schemas"]["ChangeOrderStatus"];
            /** Costdelta */
            costDelta: number;
            /** Scheduledeltadays */
            scheduleDeltaDays: number;
            /**
             * Raiseddate
             * Format: date
             */
            raisedDate: string;
        };
        /**
         * ChangeOrderStatus
         * @enum {string}
         */
        ChangeOrderStatus: "draft" | "submitted" | "approved" | "rejected";
        /**
         * CostSnapshot
         * @description A single month's baseline, forecast, and actual cost figures.
         */
        CostSnapshot: {
            /**
             * Periodmonth
             * Format: date
             */
            periodMonth: string;
            /** Workpackageid */
            workPackageId?: string | null;
            /** Baselinecost */
            baselineCost: number;
            /** Forecastcost */
            forecastCost: number;
            /** Actualcost */
            actualCost: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Milestone
         * @description A schedule milestone with dates and RAG status.
         */
        Milestone: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Planneddate
             * Format: date
             */
            plannedDate: string;
            /** Forecastdate */
            forecastDate?: string | null;
            /** Actualdate */
            actualDate?: string | null;
            ragStatus: components["schemas"]["RagStatus"];
        };
        /**
         * Project
         * @description Summary representation of a portfolio project.
         */
        Project: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Region */
            region: string;
            /** Sector */
            sector: string;
            status: components["schemas"]["ProjectStatus"];
            /**
             * Startdate
             * Format: date
             */
            startDate: string;
            /**
             * Plannedenddate
             * Format: date
             */
            plannedEndDate: string;
            /** Baselinecost */
            baselineCost: number;
            /** Currency */
            currency: string;
        };
        /**
         * ProjectDetail
         * @description Extended project view with computed cost and schedule KPIs.
         */
        ProjectDetail: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Region */
            region: string;
            /** Sector */
            sector: string;
            status: components["schemas"]["ProjectStatus"];
            /**
             * Startdate
             * Format: date
             */
            startDate: string;
            /**
             * Plannedenddate
             * Format: date
             */
            plannedEndDate: string;
            /** Baselinecost */
            baselineCost: number;
            /** Currency */
            currency: string;
            /** Actualcosttodate */
            actualCostToDate: number;
            /** Costvariance */
            costVariance: number;
            /** Scheduleslippagedays */
            scheduleSlippageDays: number;
            /** Openchangeordercount */
            openChangeOrderCount: number;
        };
        /**
         * ProjectStatus
         * @enum {string}
         */
        ProjectStatus: "planning" | "in_delivery" | "on_hold" | "complete";
        /**
         * RagStatus
         * @enum {string}
         */
        RagStatus: "red" | "amber" | "green";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listProjects: {
        parameters: {
            query?: {
                region?: string | null;
                sector?: string | null;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getCostTrend: {
        parameters: {
            query?: {
                workPackageId?: string | null;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostSnapshot"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listMilestones: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Milestone"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listChangeOrders: {
        parameters: {
            query?: {
                status?: components["schemas"]["ChangeOrderStatus"] | null;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeOrder"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getProjectBenchmarks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenchmarkComparison"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
